### ISSUE TITLE
Can you add this themes to a community-driven collection?

### ISSUE THREAD

**Issue by morpheusthewhite** [DoubleJarvis/SpicetifyThemes#1]
I recently started on GitHub a community driven collection of themes (you can find it here). Can you create a Pull Request to the repository (or, if you prefer, I can directly add it)?

**Comment by morpheusthewhite** [comment]
@DoubleJarvis

**Comment by DoubleJarvis** [comment]
I don't have any free time on my hands as of right now to bother, but feel free to add it yourself @morpheusthewhite

**Comment by morpheusthewhite** [comment]
Don't worry, I will.

Thank you
